export const searchLocators = {
    acceptSettingsLocator:  'button[jsname="b3VHJd"]', 
    searchBoxInputLocator: '#searchboxinput',
    searchBoxSearchButtonLocator: '#searchbox-searchbutton', 
    searchDirectionButtonLocator: 'button[data-value="Directions"]',
    startDestinationInputLocator: '#sb_ifc50 > input', 
    searchBestDirectionButtonLocator: 'div[data-travel_mode="6"]',
    searchVehicleDirectionButtonLocator: 'div[data-travel_mode="0"]',
    searchPublicTransportDirectionButtonLocator: 'div[data-travel_mode="3"]',
    searchWalkDirectionButtonLocator: 'div[data-travel_mode="2"]',
    searchCyclingDirectionButtonLocator: 'div[data-travel_mode="1"]',
    searchFlightDirectionButtonLocator: 'div[data-travel_mode="4"]',
    searchResultVehicleTripIconLocator: '#section-directions-trip-travel-mode-0',
    searchErrorMessageLocator: '.Q2vNVc',
    searchResultDirectionLocator: '.DUwDvf.lfPIob', 
    searchRoutePlanLocator: 'button[data-value="Directions"]',
    searchRouteSaveLocator: 'button[data-value="Save"]',
    searchRouteNearbyLocator: 'button[data-value="Nearby"]',
    searchRouteSendToPhoneLocator: 'button[data-value="Send to phone"]',
    searchRouteShareLocator: 'button[data-value="Share"]',
}